### ISSUE TITLE
Incompatible language version 15 in Helix

### ISSUE THREAD

**Issue by raikhan** [ravsii/tree-sitter-d2#102]
Hi,

Thank you for this project! I am trying to get it set up in Helix 25.01.01 on MacOS, following your README instructions. My config is:
```toml
[[language]]
name = "d2"
scope = "source.git"
file-types = ["d2"]
comment-token = "#"
roots = [""]
indent = { tab-width = 2, unit = "  " }
formatter = { command = "d2", args = ["fmt", "--stdin"] }

[[grammar]]
source = { git = "https://github.com/ravsii/tree-sitter-d2", rev = "main" }
name = "d2"
```
I ran the --health fetch and build commands and copied queries from the downloaded sources/d2/queries to .config/helix/runtime/queries/d2. With all this, Helix health check looks like this:
```bash
Configured language servers: None
Configured debug adapter: None
Configured formatter: d2
Binary for formatter: /opt/homebrew/bin/d2
Tree-sitter parser: ✓
Highlight queries: ✓
Textobject queries: ✘
Indent queries: ✘
```

In Helix log, however, I find the following error:
```
helix_core::syntax [ERROR] Could not parse queries for language "d2". 
Are your grammars out of sync? Try running 'hx --grammar fetch' and 'hx --grammar build'. 
This query could not be parsed: QueryError { row: 0, column: 0, offset: 0, message: "Incompatible language version 15. Expected minimum 13, maximum 14", kind: Language }
```

Any help you can offer would be welcome! Thanks again!

**Comment by ravsii** [comment]
So it seems like Helix is using `v0.22.x` tree-sitter, which is kind of old now. (`v0.25.x` has been released almost half a year ago)

https://github.com/helix-editor/helix/blob/d24e4fcf0fcf52055838022ea80ae1dc9712a51e/Cargo.toml#L40

I recently bumped tree-sitter from `v0.24.x` to `v0.25.x` which seems to be the problem.

https://github.com/ravsii/tree-sitter-d2/commit/0ed383b47fc38373af49901f9d4d788d0ba44318 see `package.json` and `parcer.c`'s `LANGUAGE_VERSION` const

![Image](https://github.com/user-attachments/assets/472e268a-d4c1-43df-ab9b-77c8421fbb80).

---

I guess all I can do is make a separate branch for Helix with tree-sitter `v0.24.x` that should be using language version 14.

As for now I can suggest you do a little downgrade (don't forget to copy downgraded `queries`) to `d164955bce1a5f71548e3e8ebec829167678cd6c`, which is the last version built with `v0.24`. Seems to be working fine

```toml
[[grammar]]
source = { git = "https://github.com/ravsii/tree-sitter-d2", rev = "d164955bce1a5f71548e3e8ebec829167678cd6c" }
name = "d2"
```

![Image](https://github.com/user-attachments/assets/b063f381-af6b-4762-9df8-2e1ff759bfb6)

**Comment by ravsii** [comment]
Ok that was easier than I expected.

Can you check if these options work for you? As usual, re-copy queries to `runtime/queries/d2/*` and delete and reinstall grammar.

```toml
[[grammar]]
source = { git = "https://github.com/ravsii/tree-sitter-d2", rev = "main-helix" }
name = "d2"
```

Seems to be working for me
